
name: Deployment on the server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCES_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sonnyhardy/sa-backend:latest

  server-deploy:
    name: server-deploy
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: server-deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker pull sonnyhardy/sa-backend:latest
            sudo docker stop sa-backend-1 || true
            sudo docker rm sa-backend-1 || true
            sudo docker run -d --name sa-backend-1 -p 8081:8081 sonnyhardy/sa-backend:latest

  database:
    name: database-deployment
    runs-on: ubuntu-latest
    steps:
      - name: create-deployment-folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p sa-backend-database

      - name: copy-docker-compose-file
        run: scp docker-compose.yml ${{ secrets.PRIVATE_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }}:sa-backend-database/docker-compose.yml

      - name: database-deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd sa-backend-database
            sudo docker-compose -f docker-compose.yml pull -q
            sudo docker-compose -f docker-compose.yml up -d